[package]
name = "crontab_runner"
version = "0.0.0"
edition = "2021"

[features]
default = ["runtime-tokio-native-tls"]
runtime-tokio-rustls = ["sqlx/runtime-tokio-rustls", "tokio"]
runtime-tokio-native-tls = ["sqlx/runtime-tokio-native-tls", "tokio"]

[dependencies]
crontab_types = { path = "../crontab_types" }
chrono = { version = "0.4.23", features = ["serde"] }
sqlx = { version = "0.6.2", features = ["chrono"] }
thiserror = "1.0.38"
serde = { version = "1.0.151", features = ["derive"] }
serde_json = "1.0.91"
getset = "0.1.2"
tracing = "0.1.37"
once_cell = "1.16.0"
tokio = { version = "1.23.0", features = ["time"], optional = true }
