[package]
name = "crontab_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crontab_types = { path = "../crontab_types" }
json5 = "0.4.1"
nom = "7.1.1"
serde = { version = "1.0.151", features = ["derive"] }
serde_json = "1.0.91"
serde_qs = "0.10.1"
thiserror = "1.0.38"
