[package]
name = "crontab_types"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.23"
getset = "0.1.2"
serde_json = "1.0.91"

[dev-dependencies]
anyhow = "1.0.68"
